// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--qSsuCbSfa73EwA-uE4MUg2ergJxLI0',
    appId: '1:674273818413:web:3e30447c27b22b458ac5a4',
    messagingSenderId: '674273818413',
    projectId: 'oslava-events-dev',
    authDomain: 'oslava-events-dev.firebaseapp.com',
    storageBucket: 'oslava-events-dev.firebasestorage.app',
    measurementId: 'G-Q77BET8N73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKN8ZoR2HMILVKSvWv7dAdiS2i_uIQvp8',
    appId: '1:674273818413:android:cb92ab8aa6581b6a8ac5a4',
    messagingSenderId: '674273818413',
    projectId: 'oslava-events-dev',
    storageBucket: 'oslava-events-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH_QflkDEeo5b2jeInn61tblB7OAYJ5GI',
    appId: '1:674273818413:ios:efb49d48eb11fc3f8ac5a4',
    messagingSenderId: '674273818413',
    projectId: 'oslava-events-dev',
    storageBucket: 'oslava-events-dev.firebasestorage.app',
    iosBundleId: 'com.oslavaevents.oslavaEvents',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH_QflkDEeo5b2jeInn61tblB7OAYJ5GI',
    appId: '1:674273818413:ios:efb49d48eb11fc3f8ac5a4',
    messagingSenderId: '674273818413',
    projectId: 'oslava-events-dev',
    storageBucket: 'oslava-events-dev.firebasestorage.app',
    iosBundleId: 'com.oslavaevents.oslavaEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC--qSsuCbSfa73EwA-uE4MUg2ergJxLI0',
    appId: '1:674273818413:web:241564de8654ca868ac5a4',
    messagingSenderId: '674273818413',
    projectId: 'oslava-events-dev',
    authDomain: 'oslava-events-dev.firebaseapp.com',
    storageBucket: 'oslava-events-dev.firebasestorage.app',
    measurementId: 'G-MW69M3KQPX',
  );
}
